export const UPDATE_VEHICLES = 'UPDATE_VEHICLES'
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS'
export const FETCH_VEHICLES_ACTION = 'FETCH_VEHICLES_ACTION'
export const UPDATE_PAGINATION = 'UPDATE_PAGINATION'
