// actions
export const UPDATE_VEHICLES = 'UPDATE_VEHICLES'
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS'
export const UPDATE_PAGINATION = 'UPDATE_PAGINATION'
export const VEHICLE_HOVERED = 'VEHICLE_HOVERED'
